SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(ss.SALES * b.PRICE) AS TOTAL_SALES
FROM BOOK b
JOIN AUTHOR a ON a.AUTHOR_ID = b.AUTHOR_ID
JOIN 
(
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 01
    GROUP BY BOOK_ID
) ss ON ss.BOOK_ID = b.BOOK_ID
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY b.AUTHOR_ID, b.CATEGORY DESC;