SELECT os.YEAR, os.MONTH, ui.GENDER, COUNT(*) AS USERS
FROM USER_INFO ui
JOIN
(
    SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_ID
    FROM ONLINE_SALE
    GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), USER_ID
) os ON os.USER_ID = ui.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY os.YEAR, os.MONTH, ui.GENDER
ORDER BY YEAR, MONTH, GENDER;