SELECT ROUTE, CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE, CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
# ORDER BY TOTAL_DISTANCE DES;라고 적으면 CONCAT 때문에 문자열을 기준으로 내림차순 정렬하게 됨.
ORDER BY SUM(D_BETWEEN_DIST) DESC;