SELECT *
FROM (
    SELECT ai.NAME, ai.DATETIME
    FROM ANIMAL_INS ai
    LEFT JOIN ANIMAL_OUTS ao ON ao.ANIMAL_ID = ai.ANIMAL_ID
    WHERE ao.ANIMAL_ID IS NULL
    ORDER BY ai.DATETIME
)
WHERE ROWNUM <= 3