SELECT apnt.APNT_NO, pt.PT_NAME, pt.PT_NO, dr.MCDP_CD, dr.DR_NAME, apnt.APNT_YMD
FROM APPOINTMENT apnt
JOIN DOCTOR dr ON apnt.MDDR_ID = dr.DR_ID
JOIN PATIENT pt ON apnt.PT_NO = pt.PT_NO
WHERE dr.MCDP_CD = 'CS' AND apnt.APNT_CNCL_YN = 'N' AND YEAR(apnt.APNT_YMD) = 2022 AND MONTH(apnt.APNT_YMD) = 04 AND DAY(apnt.APNT_YMD) = 13
ORDER BY apnt.APNT_YMD;