SELECT ugu.USER_ID, ugu.NICKNAME, ugb.PRICE AS TOTAL_SALES
FROM USED_GOODS_USER ugu
JOIN 
(
    SELECT WRITER_ID, SUM(PRICE) AS PRICE
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
) ugb ON ugu.USER_ID = ugb.WRITER_ID
ORDER BY TOTAL_SALES;