SELECT c.ID, c.GENOTYPE, p.GENOTYPE as PARENT_GENOTYPE
FROM ECOLI_DATA c
JOIN ECOLI_DATA p ON p.ID = c.PARENT_ID
# 일부만 포함해도 되면 != 0
# 모두 포함해야 하면 = p.GENOTYPE
WHERE (c.GENOTYPE & p.GENOTYPE) = p.GENOTYPE
order by c.ID ASC;