SELECT fi.ID, fni.FISH_NAME, fi.LENGTH
FROM FISH_INFO fi
JOIN FISH_NAME_INFO fni ON fni.FISH_TYPE = fi.FISH_TYPE
WHERE (fni.FISH_TYPE, fi.LENGTH)
    IN (SELECT FISH_TYPE, MAX(LENGTH)
       FROM FISH_INFO
       GROUP BY FISH_TYPE)
ORDER BY fi.ID;