SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE '2021-01-01' <= PUBLISHED_DATE AND PUBLISHED_dATE < '2022-01-01'
    AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE ASC;