SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, 
    CASE
        WHEN STATUS = 'SALE' THEN '판매중'
        WHEN STATUS = 'RESERVED' THEN '예약중'
        ELSE '거래완료'
    END AS STATUS
FROM USED_GOODS_BOARD
WHERE EXTRACT(YEAR FROM CAST(CREATED_DATE AS DATE)) = 2022 AND EXTRACT(MONTH FROM CAST(CREATED_DATE AS DATE)) = 10 AND EXTRACT(DAY FROM CAST(CREATED_DATE AS DATE)) = 5
ORDER BY BOARD_ID DESC;