SELECT b.CATEGORY, SUM(bs.SALES) AS TOTAL_SALES
FROM BOOK b
JOIN 
(
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 01
    GROUP BY BOOK_ID
) bs ON bs.BOOK_ID = b.BOOK_ID
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY;